export const SUBCRIPTIONS = ["subcriptions"]
export const SERVICES = ["services"]
export const PAYMENT_METHODS = ["payment-methods"]
export const CATEGORIES = ["categories"]
export const ANALYTICS_SUBSCRIPTIONS = ["analytics-subscriptions"]
export const ANALYTICS_CATEGORIES = ["analytics-categories"]
export const ANALYTICS_PAYMENTS = ["analytics-payments"]
